version: '3.1'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: playground
    ports:
      - '3306:3306'
    volumes:
      - ../sql-scripts/schema/:/docker-entrypoint-initdb.d/
      - ../sql-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      
